# Site settings
title: FedRAMP Tailored
email:
permalink: pretty
author:
  name: "???"
  email: hmmmm@gsa.gov


exclude:
- CONTRIBUTING.md
- Staticfile
- manifest.yml
- _config.yml
- .travis.yml
- .gitignore
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- vendor

sass:
  style: :compressed

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

collections:
  pages:
    output: true
    permalink: /:path/
